### PR TITLE
[hebaov2]add loopring label in all event emitted by wallet

### PR DESCRIPTION
**Pull request by kongliangzhong**

### CODE REVIEW

**Comment by Brechtpd** [comment]
Could you provide a bit more detail what this allows us to do?

**Comment by dong77** [comment]
I think I know a bit more about the reason behind this PR. Before it, we will have to listen to all events or all wallet addresses for events; with this one, we can filter based on a field with this constant value, then most events are our wallet events. It’s to make event subscription easier.

**Comment by dong77** [comment]
@kongliangzhong The Java library shall allow us to subscribe to multiple events. If that's the case, then we don't need this change at all.

**Comment by kongliangzhong** [comment]
After some discussion, we decide to use topic0 of each event as the filter. So this PR is closed.

**Pull request closed without merging**
