### PR TITLE
[tokenbank] fix  MetaTxModule's design

### PR DESCRIPTION
**Pull request by dong77**

### CODE REVIEW

**Comment by dong77** [comment]
The previous implementations requires a bind(wallet, guardian) function just for the relayed meta transaction. Now the signer is passed to executeSigned method as a parameter but the data signed by the signer doesn’t need to include the guardian param.

**Comment by dong77** [comment]
@letsgoustc please let me know if you have any feedback. Will merge only after your review.

**Comment by letsgoustc** [comment]
> @letsgoustc please let me know if you have any feedback. Will merge only after your review.

The argent's origin design only allow wallet owner to sign the meta transaction. Looks like we add one more signer variable to allow non-wallet owner?

**Comment by dong77** [comment]
The guardian can also sign meta-transactions.
Who can sign meta-transactions is totally up to the module, the point is: the singer can be any arbitrary contract address, not just external owned addresses.

**Comment by letsgoustc** [comment]
> The guardian can also sign meta-transactions.
> Who can sign meta-transactions is totally up to the module, the point is: the singer can be any arbitrary contract address, not just external owned addresses.

Got it. Agreed that our current design is more flexible to let the module to decide who can sign metaTx.

**Pull request merged**
