### PR TITLE
add GasComparision

### PR DESCRIPTION
**Pull request by dong77**

### CODE REVIEW

**Comment by kongliangzhong** [comment]
实现了一个简单的add接口，添加7个guardian，测试gas情况如下：

Impl1: 
i: 1 ; gasUsed: 42822
i: 2 ; gasUsed: 42822
i: 3 ; gasUsed: 42822
i: 4 ; gasUsed: 42822
i: 5 ; gasUsed: 42822
i: 6 ; gasUsed: 42822
i: 7 ; gasUsed: 42822

Impl2:
i: 1 ; gasUsed: 43561
i: 2 ; gasUsed: 31483
i: 3 ; gasUsed: 33240
i: 4 ; gasUsed: 34997
i: 5 ; gasUsed: 36754
i: 6 ; gasUsed: 38512
i: 7 ; gasUsed: 40269
  
第二种在一些情况下略省一些gas，但是不存储guardian，做任何判断都以来外部传入的数据（如判断isGuardian），实现所有的接口都会复杂一些。

**Comment by Brechtpd** [comment]
I'm assuming these are L1 gas costs? For an optimistic rollup the largest cost is calldata, and Impl2 needs to put all guardians in the calldata for each transaction that depends on the guardians, so my prediction would be that the cost of Impl2 to be much worse for optimistic rollups (and perhaps zk rollups, though not necessarily because it depends on how DA is enforced).

**Comment by kongliangzhong** [comment]
Yes, I agree. There is no need to do this kind of optimism.

**Comment by dong77** [comment]
Ok, then lets close this issue.

**Pull request closed without merging**
