### PR TITLE
[hebao] support multiple types of signatures.

### PR DESCRIPTION
**Pull request by dong77**
Try to solve issue https://github.com/Loopring/protocols/issues/780

### CODE REVIEW

**Comment by Brechtpd** [comment]
There's a couple of ways to do this and this is certainly a good way to do it. Some other options:

1. [EIP-2126](https://github.com/ethereum/EIPs/blob/202d578acb76bb4b8d0f46630eff4965ca61c092/EIPS/eip-2126.md): There is a sort of standard (still a draft) to support multiple signature schemes. The signature type is simply added to the end of the `bytes` array which simplifies the code a bit (no need to extract data). It doesn't support multiple signatures in a single `bytes`, but we don't need that if we simply do `bytes[] memory signatures` which is supported with `ABIEncoderV2`.
2. Do something similar to [gnosis](https://github.com/gnosis/safe-contracts/blob/78494bcdbc61b3db52308a25f0556c42cf656ab1/contracts/GnosisSafe.sol#L181). All signatures are still 65 bytes so we still have O(1) access to any signature (and you can still do `signatures.length/65` to make sure enough data can be read from the array). If a signature type needs more data it can be added to the end of the `bytes` array.

I kind of like option 1. because it keeps things very simply (no need to extract signatures from a larger `bytes` array, easy O(1) access), but all options are very similar of course so the method used in this PR is also fine with me (although it is a bit more complex and doesn't follow any standards (well, a draft standard...)).

**Comment by dong77** [comment]
Assuming each signature is 65 bytes is really a bad idea. I also like the first approach. Actually I had tried to create a PR to use `bytes[] memory signature`, but then I did some research and found that there are even [bugs](https://blog.ethereum.org/2019/03/26/solidity-optimizer-and-abiencoderv2-bug/) in ABIEncoderV2 which scares me from using it. `bytes[] memory signature` will make the interface much cleaner.

**Comment by Brechtpd** [comment]
I'm aware of the bugs with `ABIEncoderV2`, but because we don't ever store anything in the contract using `ABIEncoderV2` (which seems to be the case for these hard to detect `ABIEncoderV2` bugs as far as I'm aware) I think it's safe to use for things like this (if it's in memory and the data isn't correct it would be easy to detect while testing). There's lots of projects using `ABIEncoderV2` for a long time already (0x was already using it in V2 of their protocol more than a year ago for example).

**Comment by dong77** [comment]
I changed the code to use ABIEncoderV2 and supported https://github.com/ethereum/EIPs/blob/202d578acb76bb4b8d0f46630eff4965ca61c092/EIPS/eip-2126.md

**Pull request merged**
